# Generated by Django 4.0.4 on 2022-06-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
