# Generated by Django 4.0.5 on 2022-06-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0006_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, choices=[('selfpick', 'Самовывоз: бесплатно'), ('courier', 'Доставка курьером: 300 руб.'), ('post', 'Доставка почтой: 300 руб.')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('cash', 'Наличными при получении'), ('online', 'Банковской картой онлайн'), ('card', 'Банковской картой при получении')], max_length=20, null=True),
        ),
    ]
