# Generated by Django 4.0.4 on 2022-06-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0011_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Полный адрес'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('process', 'в обработке'), ('confirmed', 'подтвержден'), ('delivery', 'доставляется'), ('finished', 'завершен')], default='process', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
