# Generated by Django 4.0.4 on 2022-06-14 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webshop', '0012_alter_address_address_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, choices=[('selfpick', 'самовывоз, бесплатно'), ('courier', 'доставка курьером, 300 руб.'), ('post', 'доставка почтой, 300 руб.')], max_length=20, null=True, verbose_name='Доставка'),
        ),
    ]
