# Generated by Django 4.0.4 on 2022-06-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0013_alter_address_user_alter_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.FloatField(default=1),
        ),
    ]
