# Generated by Django 4.0.5 on 2022-09-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0014_order_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('expire_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('cash', 'наличными при получении'), ('online', 'банковской картой онлайн'), ('card', 'банковской картой при получении')], max_length=20, null=True, verbose_name='Оплата'),
        ),
    ]
